### ISSUE TITLE
Recommend switch to HKDF for better security

### ISSUE THREAD

**Issue by hartmantam** [tomashavlas/gnome-shell-extension-passcalc#4]
Switching to HKDF(HMAC-based Extract-and-Expand Key Derivation Function - RFC 5869) for better security. Demo JS: http://mozilla.github.io/fxa-js-client/files/client_lib_hkdf.js.html

**Comment by tomashavlas** [comment]
Good idea, do you know about some standalone javascript implementation of HKDF? Also if you are capable/willing you can implement this and make pull request. If no I take care of that once I'll have some free time.

**Comment by tomashavlas** [comment]
I've added support HKDF, and marked using old string concatenation method as deprecated, and also I'm planning to remove this old method in some future releases.
